name: CI

on:
  push:
    branches: test
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: execute build
      run: |
       docker build -t . --file Dockerfile --tag kangmin/backend:latest
    - name: docker login
      run: |
        docker login -u ${{secrets.DOCKER_USER_NAME}} --password ${{secrets.DOCKER_USER_PASSWORD}}
        docker push kangmin/backend:latest 
